{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: ingressRoute
metadata:
  name: {{ default (printf "%s-traefik" .Release.Name) .Values.ingressRoute.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ default .Release.Namespace .Values.ingressRoute.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ default "traefik" .Values.ingressRoute.ingressClass | quote }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  entryPoints:
  {{- range (default (list "websecure") .Values.ingressRoute.entryPoints) }}
    - {{ . | quote }}
  {{- end }}
  routes:
    - kind: Rule
      match: {{ required "ingressRoute.match is required" .Values.ingressRoute.match | quote }}
      services:
        - name: {{ required "ingressRoute.service.name is required" .Values.ingressRoute.service.name | quote }}
          namespace: {{ default .Release.Namespace .Values.ingressRoute.service.namespace | quote }}
          port: {{ required "ingressRoute.service.port is required" .Values.ingressRoute.service.port }}
          scheme: {{ default "http" .Values.ingressRoute.service.scheme | quote }}
{{- end }}